# Version of the Compose file format
# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.7"

# Custom services
services:

    # NGINX configuration
    nginx:
        container_name: symfony_nginx
        build: .docker/nginx
        links:
            - php
        depends_on:
            - php

    # MySQL database configuration
    mysql:
        build: .docker/mysql
        container_name: symfony_mysql
        volumes:
            - .docker/data/mysql:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    # phpMyAdmin configuration
    phpmyadmin:
        build: .docker/phpmyadmin
        container_name: symfony_phpmyadmin
        ports:
            - 8081:80
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306

    # Redis configuration
    redis:
        build: .docker/redis
        container_name: symfony_redis
        volumes:
            - .docker/data/redis:/data

    # PHP configuration
    php:
        build: .docker/php
        container_name: symfony_php
        links:
            - redis
        depends_on:
            - redis